FROM golang:1.15.3-alpine3.12

RUN echo ${MAIN}

# `skaffold debug` sets SKAFFOLD_GO_GCFLAGS to disable compiler optimizations
ARG SKAFFOLD_GO_GCFLAGS

COPY go.* /hnjobs/
COPY *.go /hnjobs/
COPY *.proto /hnjobs/
COPY pkg /hnjobs/pkg/
COPY cmd /hnjobs/cmd/

WORKDIR /hnjobs
