// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hnjobs.proto

package hnjobs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImportItemStatus int32

const (
	ImportItemStatus_DUMMY_ITEM_STATUS ImportItemStatus = 0
	ImportItemStatus_ACCEPTED          ImportItemStatus = 1
	ImportItemStatus_EXISTS            ImportItemStatus = 2
	ImportItemStatus_REJECTED          ImportItemStatus = 3
)

var ImportItemStatus_name = map[int32]string{
	0: "DUMMY_ITEM_STATUS",
	1: "ACCEPTED",
	2: "EXISTS",
	3: "REJECTED",
}

var ImportItemStatus_value = map[string]int32{
	"DUMMY_ITEM_STATUS": 0,
	"ACCEPTED":          1,
	"EXISTS":            2,
	"REJECTED":          3,
}

func (x ImportItemStatus) String() string {
	return proto.EnumName(ImportItemStatus_name, int32(x))
}

func (ImportItemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae2cc4ad0bb53991, []int{0}
}

type ImportJobStatus int32

const (
	ImportJobStatus_DUMMY_JOB_STATUS ImportJobStatus = 0
	ImportJobStatus_RUNNING          ImportJobStatus = 1
	ImportJobStatus_WAITING          ImportJobStatus = 2
	ImportJobStatus_ARCHIVED         ImportJobStatus = 3
)

var ImportJobStatus_name = map[int32]string{
	0: "DUMMY_JOB_STATUS",
	1: "RUNNING",
	2: "WAITING",
	3: "ARCHIVED",
}

var ImportJobStatus_value = map[string]int32{
	"DUMMY_JOB_STATUS": 0,
	"RUNNING":          1,
	"WAITING":          2,
	"ARCHIVED":         3,
}

func (x ImportJobStatus) String() string {
	return proto.EnumName(ImportJobStatus_name, int32(x))
}

func (ImportJobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae2cc4ad0bb53991, []int{1}
}

type ItemReference struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemReference) Reset()         { *m = ItemReference{} }
func (m *ItemReference) String() string { return proto.CompactTextString(m) }
func (*ItemReference) ProtoMessage()    {}
func (*ItemReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae2cc4ad0bb53991, []int{0}
}

func (m *ItemReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemReference.Unmarshal(m, b)
}
func (m *ItemReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemReference.Marshal(b, m, deterministic)
}
func (m *ItemReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemReference.Merge(m, src)
}
func (m *ItemReference) XXX_Size() int {
	return xxx_messageInfo_ItemReference.Size(m)
}
func (m *ItemReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemReference.DiscardUnknown(m)
}

var xxx_messageInfo_ItemReference proto.InternalMessageInfo

func (m *ItemReference) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ImportStatus struct {
	ItemStatus           ImportItemStatus `protobuf:"varint,1,opt,name=item_status,json=itemStatus,proto3,enum=hnjobs.ImportItemStatus" json:"item_status,omitempty"`
	JobStatus            ImportJobStatus  `protobuf:"varint,2,opt,name=job_status,json=jobStatus,proto3,enum=hnjobs.ImportJobStatus" json:"job_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ImportStatus) Reset()         { *m = ImportStatus{} }
func (m *ImportStatus) String() string { return proto.CompactTextString(m) }
func (*ImportStatus) ProtoMessage()    {}
func (*ImportStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae2cc4ad0bb53991, []int{1}
}

func (m *ImportStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportStatus.Unmarshal(m, b)
}
func (m *ImportStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportStatus.Marshal(b, m, deterministic)
}
func (m *ImportStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportStatus.Merge(m, src)
}
func (m *ImportStatus) XXX_Size() int {
	return xxx_messageInfo_ImportStatus.Size(m)
}
func (m *ImportStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ImportStatus proto.InternalMessageInfo

func (m *ImportStatus) GetItemStatus() ImportItemStatus {
	if m != nil {
		return m.ItemStatus
	}
	return ImportItemStatus_DUMMY_ITEM_STATUS
}

func (m *ImportStatus) GetJobStatus() ImportJobStatus {
	if m != nil {
		return m.JobStatus
	}
	return ImportJobStatus_DUMMY_JOB_STATUS
}

type JobStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae2cc4ad0bb53991, []int{2}
}

func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (m *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(m, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("hnjobs.ImportItemStatus", ImportItemStatus_name, ImportItemStatus_value)
	proto.RegisterEnum("hnjobs.ImportJobStatus", ImportJobStatus_name, ImportJobStatus_value)
	proto.RegisterType((*ItemReference)(nil), "hnjobs.ItemReference")
	proto.RegisterType((*ImportStatus)(nil), "hnjobs.ImportStatus")
	proto.RegisterType((*JobStatus)(nil), "hnjobs.JobStatus")
}

func init() {
	proto.RegisterFile("hnjobs.proto", fileDescriptor_ae2cc4ad0bb53991)
}

var fileDescriptor_ae2cc4ad0bb53991 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x29, 0x6a, 0x95, 0x01, 0xb1, 0x6c, 0x20, 0x12, 0x2e, 0x9a, 0x9e, 0x0c, 0x07, 0x48,
	0x30, 0xd1, 0x78, 0x32, 0xa5, 0x34, 0xb2, 0x24, 0x7c, 0xd8, 0x0f, 0x51, 0x2f, 0xc4, 0xc2, 0x0a,
	0x25, 0xc2, 0x92, 0xee, 0x72, 0xf0, 0xa8, 0x7f, 0xb9, 0xed, 0x2e, 0x54, 0x21, 0xf1, 0x36, 0x6f,
	0xe7, 0xbd, 0xdf, 0x74, 0x26, 0x85, 0xdc, 0x6c, 0x39, 0xa7, 0x3e, 0xab, 0xad, 0x42, 0xca, 0x29,
	0x52, 0xa5, 0xd2, 0x2f, 0xe0, 0x14, 0x73, 0xb2, 0xb0, 0xc9, 0x3b, 0x09, 0xc9, 0x72, 0x4c, 0x50,
	0x1e, 0xd2, 0xc1, 0xa4, 0xac, 0x5c, 0x2a, 0x57, 0x47, 0x76, 0x54, 0xe9, 0x5f, 0x0a, 0xe4, 0xf0,
	0x62, 0x45, 0x43, 0xee, 0xf0, 0x37, 0xbe, 0x66, 0xe8, 0x0e, 0xb2, 0x41, 0x94, 0x18, 0x31, 0x21,
	0x85, 0x33, 0xdf, 0x28, 0xd7, 0x36, 0x74, 0x69, 0x8d, 0x91, 0xd2, 0x6e, 0x43, 0x90, 0xd4, 0xe8,
	0x06, 0x20, 0x32, 0x6d, 0x93, 0x69, 0x91, 0x3c, 0xdf, 0x4d, 0x76, 0xa8, 0xbf, 0x09, 0x66, 0xe6,
	0xdb, 0x52, 0xcf, 0x42, 0x26, 0x79, 0xaf, 0x3e, 0x82, 0xb6, 0x3f, 0x04, 0x95, 0xa0, 0xd0, 0xf2,
	0xba, 0xdd, 0x97, 0x11, 0x76, 0xad, 0xee, 0xc8, 0x71, 0x0d, 0xd7, 0x73, 0xb4, 0x14, 0xca, 0xc1,
	0x89, 0x61, 0x9a, 0xd6, 0xc0, 0xb5, 0x5a, 0x9a, 0x82, 0x00, 0x54, 0xeb, 0x19, 0x3b, 0xae, 0xa3,
	0xa5, 0xe3, 0x8e, 0x6d, 0x75, 0x2c, 0x33, 0xee, 0x1c, 0x54, 0xfb, 0x70, 0xb6, 0x37, 0x1d, 0x15,
	0x41, 0x93, 0xc4, 0x4e, 0xbf, 0xf9, 0x0b, 0xcc, 0xc2, 0xb1, 0xed, 0xf5, 0x7a, 0xb8, 0xf7, 0x10,
	0xf1, 0x22, 0x31, 0x34, 0xb0, 0x1b, 0x0b, 0x01, 0x34, 0x6c, 0xb3, 0x8d, 0x9f, 0x62, 0x60, 0xe3,
	0x5b, 0x01, 0x55, 0x12, 0xd1, 0x3d, 0xe4, 0x8d, 0xc9, 0x64, 0x38, 0xa3, 0x98, 0xb5, 0x83, 0x30,
	0x58, 0x4e, 0x51, 0x29, 0xd9, 0xf8, 0xef, 0xe1, 0x2b, 0xc5, 0xdd, 0x43, 0x6c, 0x56, 0x4f, 0xa1,
	0x5b, 0xc8, 0x78, 0x2b, 0x46, 0xc4, 0xc7, 0xfd, 0x97, 0x2d, 0x6c, 0x9f, 0x93, 0x05, 0xf4, 0x54,
	0x43, 0x85, 0xc3, 0x01, 0x65, 0xbc, 0x59, 0x79, 0x2d, 0x4f, 0x03, 0x3e, 0x5b, 0xfb, 0xb5, 0x31,
	0x5d, 0xd4, 0x19, 0xf9, 0x20, 0xec, 0xb3, 0x2e, 0xfd, 0xbe, 0x2a, 0xfe, 0x86, 0xeb, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0xf9, 0xf0, 0xea, 0x1d, 0x02, 0x00, 0x00,
}
