apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: hnjobs
build:
  artifacts:
  - image: hnjobs-server
    docker:
      dockerfile: Dockerfile-server
    requires:
      - image: hnjobs-build
        alias: BUILD
      - image: hnjobs-run
        alias: RUN
  - image: hnjobs-ui
    docker:
      dockerfile: Dockerfile-ui
    requires:
      - image: hnjobs-build
        alias: BUILD
      - image: hnjobs-run
        alias: RUN
  - image: hnjobs-build
    docker:
      dockerfile: Dockerfile-build
  - image: hnjobs-run
    docker:
      dockerfile: Dockerfile-run
deploy:
  kubectl:
    manifests:
    - k8s/coredns.yaml
    - k8s/server.yaml
    - k8s/ui.yaml
