apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: hnjobs
build:
  local:
    push: false
  artifacts:
  - image: hnjobs-server
    docker:
      dockerfile: Dockerfile-server
    requires:
      - image: hnjobs-build
        alias: BUILD
      - image: hnjobs-run
        alias: RUN
  - image: hnjobs-ui
    docker:
      dockerfile: Dockerfile-ui
    requires:
      - image: hnjobs-build
        alias: BUILD
      - image: hnjobs-run
        alias: RUN
  - image: hnjobs-build
    docker:
      dockerfile: Dockerfile-build
  - image: hnjobs-run
    docker:
      dockerfile: Dockerfile-run
deploy:
  kustomize:
    paths:
    - k8s/overlays/local
