---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hnjobs-ui
  labels:
    app: hnjobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hnjobs-ui
  template:
    metadata:
      labels:
        app: hnjobs-ui
    spec:
      containers:
        - name: hnjobs-ui
          image: hnjobs-ui
          ports:
            - containerPort: 80
...
---
apiVersion: v1
kind: Service
metadata:
  name: hnjobs-ui
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: NodePort
  selector:
    app: hnjobs-ui
...
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hnjobs-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - grpc.example.com
  #   secretName: grpc-secret
  rules:
    - host: grpc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hnjobs-ui
                port:
                  number: 8080
...